
GITHUB_PATHS = {
  repo1: { block:"01-Ruby", category: "01-Programming-basics", path: "/fullstack-challenges/commits?path=01-Ruby/01-Programming-basics/01-Buddy&committer=", langage: "Ruby", Optional: "false", name:"Who's your buddy" },
  repo2: { block:"01-Ruby", category: "01-Programming-basics", path: "/fullstack-challenges/commits?path=01-Ruby/01-Programming-basics/02-Experiment-methods&committer=", langage: "Ruby", Optional: "false", name: "Experiment Methods" },
  repo3: { block:"01-Ruby", category: "01-Programming-basics", path: "/fullstack-challenges/commits?path=01-Ruby/01-Programming-basics/03-Age-in-days&committer=", langage: "Ruby", Optional: "false", name: "Age in Days" },
  repo4: { block:"01-Ruby", category: "01-Programming-basics", path: "/fullstack-challenges/commits?path=01-Ruby/01-Programming-basics/04-What-your-name&committer=", langage: "Ruby", Optional: "false", name: "What is your Name" },
  repo5: { block:"01-Ruby", category: "01-Programming-basics", path: "/fullstack-challenges/commits?path=01-Ruby/01-Programming-basics/05-Stupid-coaching&committer=", langage: "Ruby", Optional: "true", name: "Stupid Coaching" },
  repo6: { block:"01-Ruby", category: "01-Programming-basics", path: "/fullstack-challenges/commits?path=01-Ruby/01-Programming-basics/Optional-01-Colorful-Algorithm&committer=", langage: "Ruby", Optional: "true", name: "Colourful Algorithm" },
  repo7: { block:"01-Ruby", category: "01-Programming-basics", path: "/fullstack-challenges/commits?path=01-Ruby/01-Programming-basics/Optional-02-Ip-Address-Converter&committer=", langage: "Ruby", Optional: "true", name: "IP Address Converter" },
  repo8: { block:"01-Ruby", category: "01-Programming-basics", path: "/fullstack-challenges/commits?path=01-Ruby/01-Programming-basics/Optional-04-Morse-Code&committer=", langage: "Ruby", Optional: "true", name: "Morse Code" },
  repo9: { block:"01-Ruby", category: "01-Programming-basics", path: "/fullstack-challenges/commits?path=01-Ruby/01-Programming-basics/Optional-05-Valid-Brackets&committer=", langage: "Ruby", Optional: "true", name: "Valid Brackets" },
  repo10: { block:"01-Ruby", category: "02-Flow-Array", path: "/fullstack-challenges/commits?path=01-Ruby/02-Flow-Array/Optional-05-Simple-Looping-With-Recursion&committer=", langage: "Ruby", Optional: "true", name: "Recursion" },
  repo11: { block:"01-Ruby", category: "02-Flow-Array", path: "/fullstack-challenges/commits?path=01-Ruby/02-Flow-Array/Optional-04-Fizz-Buzz&committer=", langage: "Ruby", Optional: "true", name: "Fizz Buzz" },
  repo12: { block:"01-Ruby", category: "02-Flow-Array", path: "/fullstack-challenges/commits?path=01-Ruby/02-Flow-Array/Optional-03-Beer-song&committer=", langage: "Ruby", Optional: "true", name: "Beer Song" },
  repo13: { block:"01-Ruby", category: "02-Flow-Array", path: "/fullstack-challenges/commits?path=01-Ruby/02-Flow-Array/Optional-02-Shuffle&committer=", langage: "Ruby", Optional: "true", name: "Shuffle" },
  repo14: { block:"01-Ruby", category: "02-Flow-Array", path: "/fullstack-challenges/commits?path=01-Ruby/02-Flow-Array/Optional-01-Roman-numerals&committer=", langage: "Ruby", Optional: "true", name: "Roman Numerals" },
  repo15: { block:"01-Ruby", category: "02-Flow-Array", path: "/fullstack-challenges/commits?path=01-Ruby/02-Flow-Array/06-Destructive-Methods&committer=", langage: "Ruby", Optional: "false", name: "Destructive Methods" },
  repo16: { block:"01-Ruby", category: "02-Flow-Array", path: "/fullstack-challenges/commits?path=01-Ruby/02-Flow-Array/05-Debug-Gym&committer=", langage: "Ruby", Optional: "false", name: "Debug Gym" },
  repo17: { block:"01-Ruby", category: "02-Flow-Array", path: "/fullstack-challenges/commits?path=01-Ruby/02-Flow-Array/04-Black-Jack&committer=", langage: "Ruby", Optional: "false", name: "Black Jack" },
  repo18: { block:"01-Ruby", category: "02-Flow-Array", path: "/fullstack-challenges/commits?path=01-Ruby/02-Flow-Array/03-Sorting-the-wagon&committer=", langage: "Ruby", Optional: "false", name: "Sorting the Wagon" },
  repo19: { block:"01-Ruby", category: "02-Flow-Array", path: "/fullstack-challenges/commits?path=01-Ruby/02-Flow-Array/02-Simple-looping&committer=", langage: "Ruby", Optional: "false", name: "Simple Looping" },
  repo20: { block:"01-Ruby", category: "02-Flow-Array", path: "/fullstack-challenges/commits?path=01-Ruby/02-Flow-Array/01-Can-you-vote&committer=", langage: "Ruby", Optional: "false", name: "Can you vote ?" },
  repo21: { block:"01-Ruby", category: "03-Iterators-Blocks", path: "/fullstack-challenges/commits?path=01-Ruby/03-Iterators-Blocks/01-How-many-team-members&committer=", langage: "Ruby", Optional: "false", name: "Team Members" },
  repo22: { block:"01-Ruby", category: "03-Iterators-Blocks", path: "/fullstack-challenges/commits?path=01-Ruby/03-Iterators-Blocks/02-Enumerable&committer=", langage: "Ruby", Optional: "false", name: "Enumerable Methods" },
  repo23: { block:"01-Ruby", category: "03-Iterators-Blocks", path: "/fullstack-challenges/commits?path=01-Ruby/03-Iterators-Blocks/03-Burger-restaurant&committer=", langage: "Ruby", Optional: "false", name: "Burger Restaurant"},
  repo24: { block:"01-Ruby", category: "03-Iterators-Blocks", path: "/fullstack-challenges/commits?path=01-Ruby/03-Iterators-Blocks/04-HTML-generator&committer=", langage: "Ruby", Optional: "false", name: "HTML Generator" },
  repo25: { block:"01-Ruby", category: "03-Iterators-Blocks", path: "/fullstack-challenges/commits?path=01-Ruby/03-Iterators-Blocks/05-Splitter&committer=", langage: "Ruby", Optional: "false", name: "Splitter" },
  repo26: { block:"01-Ruby", category: "03-Iterators-Blocks", path: "/fullstack-challenges/commits?path=01-Ruby/03-Iterators-Blocks/06-Playing-with-strings&committer=", langage: "Ruby", Optional: "false", name: "Playing with Strings" },
  repo27: { block:"01-Ruby", category: "03-Iterators-Blocks", path: "/fullstack-challenges/commits?path=01-Ruby/03-Iterators-Blocks/Optional-01-Louchebem&committer=", langage: "Ruby", Optional: "true", name: "Louchebem" },
  repo28: { block:"01-Ruby", category: "03-Iterators-Blocks", path: "/fullstack-challenges/commits?path=01-Ruby/03-Iterators-Blocks/Optional-02-Storing-blocks-in-Proc&committer=", langage: "Ruby", Optional: "true", name: "Storing Blocks in Proc" },
  repo29: { block:"01-Ruby", category: "03-Iterators-Blocks", path: "/fullstack-challenges/commits?path=01-Ruby/03-Iterators-Blocks/Optional-03-A-custom-map&committer=", langage: "Ruby", Optional: "true", name: "A Custom Map" },
  repo30: { block:"01-Ruby", category: "04-Hash-Symbols", path: "/fullstack-challenges/commits?path=01-Ruby/04-Hash-Symbols/01-Modeling-with-Hash&committer=", langage: "Ruby", Optional: "false", name: "Burger Hash" },
  repo31: { block:"01-Ruby", category: "04-Hash-Symbols", path: "/fullstack-challenges/commits?path=01-Ruby/04-Hash-Symbols/02-Modeling-with-Hash-part-II&committer=", langage: "Ruby", Optional: "false", name: "Burger Hash (Part II)" },
  repo32: { block:"01-Ruby", category: "04-Hash-Symbols", path: "/fullstack-challenges/commits?path=01-Ruby/04-Hash-Symbols/03-On-symbols&committer=", langage: "Ruby", Optional: "false", name: "Quizz on Symbols" },
  repo33: { block:"01-Ruby", category: "04-Hash-Symbols", path: "/fullstack-challenges/commits?path=01-Ruby/04-Hash-Symbols/04-Argument-order-dependency&committer=", langage: "Ruby", Optional: "false", name: "Argument Order Dependency" },
  repo34: { block:"01-Ruby", category: "04-Hash-Symbols", path: "/fullstack-challenges/commits?path=01-Ruby/04-Hash-Symbols/05-Array-to-hash&committer=", langage: "Ruby", Optional: "false", name: "Array to Hash" },
  repo35: { block:"01-Ruby", category: "04-Hash-Symbols", path: "/fullstack-challenges/commits?path=01-Ruby/04-Hash-Symbols/Optional-01-Roman-to-integer&committer=", langage: "Ruby", Optional: "true", name: "Roman to Integer" },
  repo36: { block:"01-Ruby", category: "04-Hash-Symbols", path: "/fullstack-challenges/commits?path=01-Ruby/04-Hash-Symbols/Optional-02-Combine-anagrams&committer=", langage: "Ruby", Optional: "true", name: "Combine Anagrams" },
  repo37: { block:"01-Ruby", category: "04-Hash-Symbols", path: "/fullstack-challenges/commits?path=01-Ruby/04-Hash-Symbols/Optional-03-Shopping-Cart&committer=", langage: "Ruby", Optional: "true", name: "Shopping Cart" },
  repo38: { block:"01-Ruby", category:"05-Regular-Expressions", path: "/fullstack-challenges/commits?path=01-Ruby/05-Regular-Expressions/01-Phone-regexp&committer=", langage: "Ruby", Optional: "false", name: "Phone Regexp" },
  repo39: { block:"01-Ruby", category:"05-Regular-Expressions", path: "/fullstack-challenges/commits?path=01-Ruby/05-Regular-Expressions/02-Marketing-campaign&committer=", langage: "Ruby", Optional: "false", name: "Marketing Campaign" },
  repo40: { block:"01-Ruby", category:"05-Regular-Expressions", path: "/fullstack-challenges/commits?path=01-Ruby/05-Regular-Expressions/03-Word-frequency&committer=", langage: "Ruby", Optional: "false", name: "Word Frequency" },
  repo41: { block:"01-Ruby", category:"05-Regular-Expressions", path: "/fullstack-challenges/commits?path=01-Ruby/05-Regular-Expressions/04-Double-Rainbow&committer=", langage: "Ruby", Optional: "false", name: "Double Rainbow" },
  repo42: { block:"01-Ruby", category:"05-Regular-Expressions", path: "/fullstack-challenges/commits?path=01-Ruby/05-Regular-Expressions/Optional-01-Regex-Games&committer=", langage: "Ruby", Optional: "true", name: "Regex Games" },
  repo43: { block:"01-Ruby", category:"05-Regular-Expressions", path: "/fullstack-challenges/commits?path=01-Ruby/05-Regular-Expressions/Reboot-01-Calculator&committer=", langage: "Ruby", Optional: "true", name: "Calculator" },
  repo44: { block:"01-Ruby", category:"05-Regular-Expressions", path: "/fullstack-challenges/commits?path=01-Ruby/05-Regular-Expressions/Reboot-02-Horse-race&committer=", langage: "Ruby", Optional: "true", name: "Horse Race" },
  repo45: { block:"01-Ruby", category:"05-Regular-Expressions", path: "/fullstack-challenges/commits?path=01-Ruby/05-Regular-Expressions/Reboot-03-Instacart&committer=", langage: "Ruby", Optional: "true", name: "Instacart" },
  repo46: { block:"01-Ruby", category:"06-Parsing", path: "/fullstack-challenges/commits?path=01-Ruby/06-Parsing/01-CSV-Parsing&committer=", langage: "Ruby", Optional: "false", name: "CSV Parsing" },
  repo47: { block:"01-Ruby", category:"06-Parsing", path: "/fullstack-challenges/commits?path=01-Ruby/06-Parsing/02-Numbers-and-Letters&committer=", langage: "Ruby", Optional: "false", name: "Numbers and Letters" },
  repo48: { block:"01-Ruby", category:"06-Parsing", path: "/fullstack-challenges/commits?path=01-Ruby/06-Parsing/Optional-01-Text-Analyzer&committer=", langage: "Ruby", Optional: "true", name: "Text Analyser" },
  repo49: { block:"01-Ruby", category:"06-Parsing", path: "/fullstack-challenges/commits?path=01-Ruby/06-Parsing/Optional-02-Your-First-Scraper&committer=", langage: "Ruby", Optional: "true", name: "Your First Scraper" },
  repo50: { block:"01-Ruby", category:"06-Parsing", path: "/fullstack-challenges/commits?path=01-Ruby/06-Parsing/Optional-03-Time-complexity&committer=", langage: "Ruby", Optional: "true", name: "Time Complexity" },
  repo51: { block:"01-Ruby", category:"06-Parsing", path: "/fullstack-challenges/commits?path=01-Ruby/06-Parsing/Reboot-01-Christmas-list&committer=", langage: "Ruby", Optional: "true", name: "Christmas List" },
  repo52: { block:"02-OOP", category:"01-OO-Basics", path: "/fullstack-challenges/commits?path=02-OOP/01-OO-Basics/01-Define-your-own-class&committer=", langage: "Ruby", Optional: "false", name: "Define your own Class" },
  repo53: { block:"02-OOP", category:"01-OO-Basics", path: "/fullstack-challenges/commits?path=02-OOP/01-OO-Basics/02-Getters-and-Setters&committer=", langage: "Ruby", Optional: "false", name: "Getters and Setters" },
  repo54: { block:"02-OOP", category:"01-OO-Basics", path: "/fullstack-challenges/commits?path=02-OOP/01-OO-Basics/03-Basic-OOP&committer=", langage: "Ruby", Optional: "false", name: "Basic OOP"},
  repo55: { block:"02-OOP", category:"01-OO-Basics", path: "/fullstack-challenges/commits?path=02-OOP/01-OO-Basics/04-Public-Interface&committer=", langage: "Ruby", Optional: "false", name: "Public Interface" },
  repo56: { block:"02-OOP", category:"01-OO-Basics", path: "/fullstack-challenges/commits?path=02-OOP/01-OO-Basics/Optional-01-Richest-Student&committer=", langage: "Ruby", Optional: "true", name: "Richest Student" },
  repo57: { block:"02-OOP", category:"01-OO-Basics", path: "/fullstack-challenges/commits?path=02-OOP/01-OO-Basics/Optional-02-Method-Missing&committer=", langage: "Ruby", Optional: "true", name: "Method Missing" },
  repo58: { block:"02-OOP", category:"02-OO-Advanced", path: "/fullstack-challenges/commits?path=02-OOP/02-OO-Advanced/01-Dog-inheritance&committer=", langage: "Ruby", Optional: "false", name: "Dog Inheritance" },
  repo59: { block:"02-OOP", category:"02-OO-Advanced", path: "/fullstack-challenges/commits?path=02-OOP/02-OO-Advanced/02-Dessert-inheritance&committer=", langage: "Ruby", Optional: "false", name: "Dessert Inheritance" },
  repo60: { block:"02-OOP", category:"02-OO-Advanced", path: "/fullstack-challenges/commits?path=02-OOP/02-OO-Advanced/02-Farming-Diary-Crops&committer=", langage: "Ruby", Optional: "false", name: "Farming Diary Crops" },
  repo61: { block:"02-OOP", category:"02-OO-Advanced", path: "/fullstack-challenges/commits?path=02-OOP/02-OO-Advanced/03-Farming-Diary-Animals&committer=", langage: "Ruby", Optional: "false", name: "Farming Diary Animals" },
  repo62: { block:"02-OOP", category:"02-OO-Advanced", path: "/fullstack-challenges/commits?path=02-OOP/02-OO-Advanced/04-Instance-vs-Class&committer=", langage: "Ruby", Optional: "false", name: "Instance vs Class" },
  repo63: { block:"02-OOP", category:"02-OO-Advanced", path: "/fullstack-challenges/commits?path=02-OOP/02-OO-Advanced/05-About-self&committer=", langage: "Ruby", Optional: "false", name: "About Self" },
  repo64: { block:"02-OOP", category:"02-OO-Advanced", path: "/fullstack-challenges/commits?path=02-OOP/02-OO-Advanced/Optional-01-Web-Browser&committer=", langage: "Ruby", Optional: "true", name: "Web Browser"  },
  repo65: { block:"02-OOP", category:"02-OO-Advanced", path: "/fullstack-challenges/commits?path=02-OOP/02-OO-Advanced/Optional-02-Gosu-Game&committer=", langage: "Ruby", Optional: "true", name: "Gosu Game" },
  repo66: { block:"02-OOP", category:"02-OO-Advanced", path: "/fullstack-challenges/commits?path=02-OOP/02-OO-Advanced/Optional-03-Farming-Diary-Game&committer=", langage: "Ruby", Optional: "true", name: "Farming Diary Game" },
  repo67: { block:"02-OOP", category:"02-OO-Advanced", path: "/fullstack-challenges/commits?path=02-OOP/02-OO-Advanced/Optional-04-Tracking-Subclasses&committer=", langage: "Ruby", Optional: "true", name: "Tracking Subclasses" },
  repo68: { block:"02-OOP", category:"03-Cookbook", path: "/fullstack-challenges/commits?path=02-OOP/03-Cookbook/01-Recipe&committer=", langage: "Ruby", Optional: "false",  name: "Start with the Model" },
  repo69: { block:"02-OOP", category:"03-Cookbook", path: "/fullstack-challenges/commits?path=02-OOP/03-Cookbook/02-Cookbook&committer=", langage: "Ruby", Optional: "false",  name: "Cookbook" },
  repo70: { block:"02-OOP", category:"03-Cookbook", path: "/fullstack-challenges/commits?path=02-OOP/03-Cookbook/03-Cookbook-With-CSV&committer=", langage: "Ruby", Optional: "false",  name: "Cookbook with CSV" },
  repo71: { block:"02-OOP", category:"03-Cookbook", path: "/fullstack-challenges/commits?path=02-OOP/03-Cookbook/04-Cookbook-With-Scraping&committer=", langage: "Ruby", Optional: "false",  name: "Cookbook with Scraping" },
  repo72: { block:"02-OOP", category:"03-Cookbook", path: "/fullstack-challenges/commits?path=02-OOP/03-Cookbook/Optional-01-Medium-pocket&committer=", langage: "Ruby", Optional: "true",  name: "Pocket Reader" },
  repo73: { block:"02-OOP", category:"03-Cookbook", path: "/fullstack-challenges/commits?path=02-OOP/03-Cookbook/Optional-02-Sinatra&committer=", langage: "Ruby", Optional: "true",  name: "Cookbook Web App" },
  repo74: { block:"02-OOP", category:"04-Food-Delivery-Day-One", path: "/fullstack-challenges/commits?path=02-OOP/04-Food-Delivery-Day-One/01-Food-Delivery&committer=", langage: "Ruby", Optional: "false",  name: "Food Delivery Day 1" },
  repo75: { block:"02-OOP", category:"04-Food-Delivery-Day-One", path: "/fullstack-challenges/commits?path=02-OOP/04-Food-Delivery-Day-One/Optional-01-Medium-pocket-part-two&committer=", langage: "Ruby", Optional: "true",  name: "Pocket Reader (extended)" },
  repo76: { block:"02-OOP", category:"05-Food-Delivery-Day-Two", path: "/fullstack-challenges/commits?path=02-OOP/05-Food-Delivery-Day-Two/01-Food-Delivery&committer=", langage: "Ruby", Optional: "false",  name: "Food Delivery Day 2" },
  repo77: { block:"03-AR-Database", category:"01-DB-and-SQL", path: "/fullstack-challenges/commits?path=03-AR-Database/01-DB-and-SQL/01-DB-design&committer=", langage: "Database", Optional: "false",  name: "DB Design" },
  repo78: { block:"03-AR-Database", category:"01-DB-and-SQL", path: "/fullstack-challenges/commits?path=03-AR-Database/01-DB-and-SQL/02-Interacting-with-db&committer=", langage: "Database", Optional: "false", name: "Interacting with DB" },
  repo79: { block:"03-AR-Database", category:"01-DB-and-SQL", path: "/fullstack-challenges/commits?path=03-AR-Database/01-DB-and-SQL/03-Interacting-with-code&committer=", langage: "Database", Optional: "false", name: "Interacting with Code" },
  repo80: { block:"03-AR-Database", category:"01-DB-and-SQL", path: "/fullstack-challenges/commits?path=03-AR-Database/01-DB-and-SQL/04-CRUD-Read&committer=", langage: "Database", Optional: "false", name: "CRUD Read" },
  repo81: { block:"03-AR-Database", category:"01-DB-and-SQL", path: "/fullstack-challenges/commits?path=03-AR-Database/01-DB-and-SQL/Optional-01-CRUD-Advanced&committer=", langage: "Database", Optional: "true", name: "CRUD Advanced"},
  repo82: { block:"03-AR-Database", category:"01-DB-and-SQL", path: "/fullstack-challenges/commits?path=03-AR-Database/01-DB-and-SQL/Optional-02-SQL-queries&committer=", langage: "Database", Optional: "true", name: "SQL Queries" },
  repo83: { block:"03-AR-Database", category:"01-DB-and-SQL", path: "/fullstack-challenges/commits?path=03-AR-Database/01-DB-and-SQL/Optional-03-MVC-HackerNews&committer=", langage: "Database", Optional: "true", name: "MVC HackerNews" },
  repo84: { block:"03-AR-Database", category:"01-DB-and-SQL", path: "/fullstack-challenges/commits?path=03-AR-Database/01-DB-and-SQL/Optional-04-Jukebox-Sinatra&committer=", langage: "Database", Optional: "true", name: "Jukebox Sinatra" },
  repo85: { block:"03-AR-Database", category:"01-DB-and-SQL", path: "/fullstack-challenges/commits?path=03-AR-Database/01-DB-and-SQL/Optional-05-My-First-ORM&committer=", langage: "Database", Optional: "true", name: "My First ORM" },
  repo86: { block:"03-AR-Database", category:"02-ActiveRecord-Basics", path: "/fullstack-challenges/commits?path=03-AR-Database/02-ActiveRecord-Basics/01-Create-a-DB&committer=", langage: "Database", Optional: "false", name: "Generate DB" },
  repo87: { block:"03-AR-Database", category:"02-ActiveRecord-Basics", path: "/fullstack-challenges/commits?path=03-AR-Database/02-ActiveRecord-Basics/02-Migrations&committer=", langage: "Database", Optional: "false", name: "Migrations" },
  repo88: { block:"03-AR-Database", category:"02-ActiveRecord-Basics", path: "/fullstack-challenges/commits?path=03-AR-Database/02-ActiveRecord-Basics/03-Models&committer=", langage: "Database", Optional: "false", name: "Models" },
  repo89: { block:"03-AR-Database", category:"02-ActiveRecord-Basics", path: "/fullstack-challenges/commits?path=03-AR-Database/02-ActiveRecord-Basics/04-Seed-Faker&committer=", langage: "Database", Optional: "false", name: "Seed Faker" },
  repo90: { block:"03-AR-Database", category:"02-ActiveRecord-Basics", path: "/fullstack-challenges/commits?path=03-AR-Database/02-ActiveRecord-Basics/05-Seed-API&committer=", langage: "Database", Optional: "false", name: "Seed API" },
  repo91: { block:"03-AR-Database", category:"02-ActiveRecord-Basics", path: "/fullstack-challenges/commits?path=03-AR-Database/02-ActiveRecord-Basics/Optional-01-Mapping-Existing-Database&committer=", langage: "Database", Optional: "true", name: "Mapping Existing DataBase" },
  repo92: { block:"03-AR-Database", category:"02-ActiveRecord-Basics", path: "/fullstack-challenges/commits?path=03-AR-Database/02-ActiveRecord-Basics/Optional-02-Mapping-Dirty-Database&committer=", langage: "Database", Optional: "true", name: "Mapping Dirty Database" },
  repo93: { block:"03-AR-Database", category:"03-ActiveRecord-Advanced", path: "/fullstack-challenges/commits?path=03-AR-Database/03-ActiveRecord-Advanced/01-Associations&committer=", langage: "Database", Optional: "false", name: "Associations" },
  repo94: { block:"03-AR-Database", category:"03-ActiveRecord-Advanced", path: "/fullstack-challenges/commits?path=03-AR-Database/03-ActiveRecord-Advanced/02-Validations&committer=", langage: "Database", Optional: "false", name: "Validations" },
  repo95: { block:"03-AR-Database", category:"03-ActiveRecord-Advanced", path: "/fullstack-challenges/commits?path=03-AR-Database/03-ActiveRecord-Advanced/03-Sinatra&committer=", langage: "Database", Optional: "false", name: "Sinatra" },
  repo96: { block:"03-AR-Database", category:"03-ActiveRecord-Advanced", path: "/fullstack-challenges/commits?path=03-AR-Database/03-ActiveRecord-Advanced/Optional-01-Reading-Material&committer=", langage: "Database", Optional: "true", name: "Reading Material"},
  repo97: { block:"04-Front-End", category:"01-HTML-and-CSS", path: "/fullstack-challenges/commits?path=04-Front-End/01-HTML-and-CSS/01-Profile-content&committer=", langage: "HTML/CSS", Optional: "false", name: "Profile Content" },
  repo98: { block:"04-Front-End", category:"01-HTML-and-CSS", path: "/fullstack-challenges/commits?path=04-Front-End/01-HTML-and-CSS/02-Fonts-and-colors&committer=", langage: "HTML/CSS", Optional: "false", name: "Fonts and Colours" },
  repo99: { block:"04-Front-End", category:"01-HTML-and-CSS", path: "/fullstack-challenges/commits?path=04-Front-End/01-HTML-and-CSS/03-Finishing-profile-design&committer=", langage: "HTML/CSS", Optional: "false", name: "Finishing Profile Design" },
  repo100: { block:"04-Front-End", category:"01-HTML-and-CSS", path: "/fullstack-challenges/commits?path=04-Front-End/01-HTML-and-CSS/04-Responsive-profile&committer=", langage: "HTML/CSS", Optional: "false", name: "Responsive Profile" },
  repo101: { block:"04-Front-End", category:"01-HTML-and-CSS", path: "/fullstack-challenges/commits?path=04-Front-End/01-HTML-and-CSS/05-Push-on-Github-Pages&committer=", langage: "HTML/CSS", Optional: "false", name: "Push to GitHub Pages" },
  repo102: { block:"04-Front-End", category:"01-HTML-and-CSS", path: "/fullstack-challenges/commits?path=04-Front-End/01-HTML-and-CSS/06-Medium-copycat&committer=", langage: "HTML/CSS", Optional: "false", name: "Medium Copycat" },
  repo103: { block:"04-Front-End", category:"02-CSS-components", path: "/fullstack-challenges/commits?path=04-Front-End/02-CSS-components/01-Button-sprint&committer=", langage: "HTML/CSS", Optional: "false", name: "Button Sprint" },
  repo104: { block:"04-Front-End", category:"02-CSS-components", path: "/fullstack-challenges/commits?path=04-Front-End/02-CSS-components/02-Card-sprint&committer=", langage: "HTML/CSS", Optional: "false", name: "Card Sprint" },
  repo105: { block:"04-Front-End", category:"02-CSS-components", path: "/fullstack-challenges/commits?path=04-Front-End/02-CSS-components/03-Landing-page&committer=", langage: "HTML/CSS", Optional: "false", name: "Landing Page Design" },
  repo106: { block:"04-Front-End", category:"02-CSS-components", path: "/fullstack-challenges/commits?path=04-Front-End/02-CSS-components/04-Activity-feed&committer=", langage: "HTML/CSS", Optional: "false", name: "Dribble Activity Feed" },
  repo107: { block:"04-Front-End", category:"02-CSS-components", path: "/fullstack-challenges/commits?path=04-Front-End/02-CSS-components/05-Open-component-challenge&committer=", langage: "HTML/CSS", Optional: "false", name: "Copycat Challenge" },
  repo108: { block:"04-Front-End", category:"02-CSS-components", path: "/fullstack-challenges/commits?path=04-Front-End/02-CSS-components/06-Take-away&committer=", langage: "HTML/CSS", Optional: "false", name: "Take Away" },
  repo109: { block:"04-Front-End", category:"03-Bootstrap", path: "/fullstack-challenges/commits?path=04-Front-End/03-Bootstrap/01-Smiley-grids&committer=", langage: "HTML/CSS", Optional: "false", name: "Smiley Grid" },
  repo110: { block:"04-Front-End", category:"03-Bootstrap", path: "/fullstack-challenges/commits?path=04-Front-End/03-Bootstrap/02-Bootstrap-prototyping&committer=", langage: "HTML/CSS", Optional: "false", name: "Bootstap Prototyping" },
  repo111: { block:"04-Front-End", category:"03-Bootstrap", path: "/fullstack-challenges/commits?path=04-Front-End/03-Bootstrap/03-Bootstrap-forms&committer=", langage: "HTML/CSS", Optional: "false", name: "Bootstrap Forms" },
  repo112: { block:"04-Front-End", category:"03-Bootstrap", path: "/fullstack-challenges/commits?path=04-Front-End/03-Bootstrap/04-Map-layout&committer=", langage: "HTML/CSS", Optional: "false", name: "Map Layout" },
  repo113: { block:"04-Front-End", category:"03-Bootstrap", path: "/fullstack-challenges/commits?path=04-Front-End/03-Bootstrap/Optional-01-Slack-copycat&committer=", langage: "HTML/CSS", Optional: "true", name: "Slack" },
  repo114: { block:"04-Front-End", category:"03-Bootstrap", path: "/fullstack-challenges/commits?path=04-Front-End/03-Bootstrap/Optional-02-Accessibility&committer=", langage: "HTML/CSS", Optional: "true", name: "Accessibility" },
  repo115: { block:"04-Front-End", category:"04-JS-and-DOM", path: "/fullstack-challenges/commits?path=04-Front-End/04-JS-and-DOM/01-Even-or-odd&committer=", langage: "Javascript", Optional: "false", name: "Even or Odd" },
  repo116: { block:"04-Front-End", category:"04-JS-and-DOM", path: "/fullstack-challenges/commits?path=04-Front-End/04-JS-and-DOM/02-Select-element&committer=", langage: "Javascript", Optional: "false", name: "Select an element!" },
  repo117: { block:"04-Front-End", category:"04-JS-and-DOM", path: "/fullstack-challenges/commits?path=04-Front-End/04-JS-and-DOM/03-DOM-Manipulation&committer=", langage: "Javascript", Optional: "false", name: "DOM Manipulation" },
  repo118: { block:"04-Front-End", category:"04-JS-and-DOM", path: "/fullstack-challenges/commits?path=04-Front-End/04-JS-and-DOM/04-Fake-Inbox&committer=", langage: "Javascript", Optional: "false", name: "Fake Inbox" },
  repo119: { block:"04-Front-End", category:"04-JS-and-DOM", path: "/fullstack-challenges/commits?path=04-Front-End/04-JS-and-DOM/05-JS-puzzle&committer=", langage: "Javascript", Optional: "false", name: "JS Puzzle" },
  repo120: { block:"04-Front-End", category:"04-JS-and-DOM", path: "/fullstack-challenges/commits?path=04-Front-End/04-JS-and-DOM/Optional-01-Split-The-Bill&committer=", langage: "Javascript", Optional: "true", name: "Split the bill" },
  repo121: { block:"04-Front-End", category:"05-Events-and-Iterators", path: "/fullstack-challenges/commits?path=04-Front-End/05-Events-and-Iterators/01-Unordered-list&committer=", langage: "Javascript", Optional: "false", name: "List Generator" },
  repo122: { block:"04-Front-End", category:"05-Events-and-Iterators", path: "/fullstack-challenges/commits?path=04-Front-End/05-Events-and-Iterators/02-My-First-Event-Listener&committer=", langage: "Javascript", Optional: "false", name: "My first Event Listener!" },
  repo123: { block:"04-Front-End", category:"05-Events-and-Iterators", path: "/fullstack-challenges/commits?path=04-Front-End/05-Events-and-Iterators/03-Lottery-Scratchcards&committer=", langage: "Javascript", Optional: "false", name: "Lottery Scratchcards" },
  repo124: { block:"04-Front-End", category:"05-Events-and-Iterators", path: "/fullstack-challenges/commits?path=04-Front-End/05-Events-and-Iterators/04-Wagon-Race&committer=", langage: "Javascript", Optional: "false", name: "Wagon Race" },
  repo125: { block:"04-Front-End", category:"05-Events-and-Iterators", path: "/fullstack-challenges/commits?path=04-Front-End/05-Events-and-Iterators/05-Pitch-Preparation&committer=", langage: "Javascript", Optional: "false", name: "Pitch Preparation" },
  repo126: { block:"04-Front-End", category:"05-Events-and-Iterators", path: "/fullstack-challenges/commits?path=04-Front-End/05-Events-and-Iterators/Optional-01-Minesweeper&committer=", langage: "Javascript", Optional: "true", name: "Minesweeper" },
  repo127: { block:"04-Front-End", category:"05-Events-and-Iterators", path: "/fullstack-challenges/commits?path=04-Front-End/05-Events-and-Iterators/Optional-02-Flex-Panels&committer=", langage: "Javascript", Optional: "true", name: "Flex Panels" },
  repo128: { block:"04-Front-End", category:"06-HTTP-and-API", path: "/fullstack-challenges/commits?path=04-Front-End/06-HTTP-and-API/01-Click-me&committer=", langage: "Javascript", Optional: "false", name: "Click me!" },
  repo129: { block:"04-Front-End", category:"06-HTTP-and-API", path: "/fullstack-challenges/commits?path=04-Front-End/06-HTTP-and-API/02-My-Favourite-Sports&committer=", langage: "Javascript", Optional: "false", name: "My Favourite Sports" },
  repo130: { block:"04-Front-End", category:"06-HTTP-and-API", path: "/fullstack-challenges/commits?path=04-Front-End/06-HTTP-and-API/03-Geocoder&committer=", langage: "Javascript", Optional: "false", name: "Geocoder" },
  repo131: { block:"04-Front-End", category:"06-HTTP-and-API", path: "/fullstack-challenges/commits?path=04-Front-End/06-HTTP-and-API/04-The-Fork-Restaurants&committer=", langage: "Javascript", Optional: "false", name: "The Fork Restaurant" },
  repo132: { block:"04-Front-End", category:"06-HTTP-and-API", path: "/fullstack-challenges/commits?path=04-Front-End/06-HTTP-and-API/05-Weather&committer=", langage: "Javascript", Optional: "false", name: "Weather" },
  repo133: { block:"04-Front-End", category:"07-AJAX", path: "/fullstack-challenges/commits?path=04-Front-End/07-AJAX/01-Name-Age&committer=", langage: "Javascript", Optional: "false", name: "Dictionary" },
  repo134: { block:"04-Front-End", category:"07-AJAX", path: "/fullstack-challenges/commits?path=04-Front-End/07-AJAX/02-AJAX-Autocomplete&committer=", langage: "Javascript", Optional: "false", name: "AJAX Autocomplete" },
  repo135: { block:"04-Front-End", category:"07-AJAX", path: "/fullstack-challenges/commits?path=04-Front-End/07-AJAX/03-Anonymous-Chat&committer=", langage: "Javascript", Optional: "false", name: "Anonymous Chat" },
  repo136: { block:"04-Front-End", category:"07-AJAX", path: "/fullstack-challenges/commits?path=04-Front-End/07-AJAX/04-Ajax-Search&committer=", langage: "Javascript", Optional: "false", name: "AJAX Search" },
  repo137: { block:"04-Front-End", category:"07-AJAX", path: "/fullstack-challenges/commits?path=04-Front-End/07-AJAX/Optional-01-Recipe-Book&committer=", langage: "Javascript", Optional: "true", name: "Recipe Book" },
  repo138: { block:"04-Front-End", category:"08-Templating", path: "/fullstack-challenges/commits?path=04-Front-End/08-Templating/01-Vanilla-Todo-List-Warmup&committer=", langage: "Javascript", Optional: "false", name: "Warmup" },
  repo139: { block:"04-Front-End", category:"08-Templating", path: "/fullstack-challenges/commits?path=04-Front-End/08-Templating/02-Vanilla-Todo-List&committer=", langage: "Javascript", Optional: "false", name: "Todo List in Vanilla JS" },
  repo140: { block:"04-Front-End", category:"08-Templating", path: "/fullstack-challenges/commits?path=04-Front-End/08-Templating/03-Recipes-Mustache&committer=", langage: "Javascript", Optional: "false", name: "Recipe in Mustache.js" },
  repo141: { block:"04-Front-End", category:"08-Templating", path: "/fullstack-challenges/commits?path=04-Front-End/08-Templating/04-Todo-List-Vue&committer=", langage: "Vue", Optional: "false", name: "Todo in Vue.js" },
  repo142: { block:"04-Front-End", category:"08-Templating", path: "/fullstack-challenges/commits?path=04-Front-End/08-Templating/Optional-01-Todo-List-React&committer=", langage: "React", Optional: "true", name: "Todo List in React" },
  repo143: { block:"04-Front-End", category:"08-Templating", path: "/fullstack-challenges/commits?path=04-Front-End/08-Templating/Optional-02-React-Quote-Generator&committer=", langage: "React", Optional: "true", name: "React Quote Generator" },
  repo144: { block:"04-Front-End", category:"09-Stimulus-JS", path: "/fullstack-challenges/commits?path=04-Front-End/09-Stimulus-JS/01-My-First-Event-Listener&committer=", langage: "Javascript", Optional: "false", name: "Stimulus Warmup" },
  repo145: { block:"04-Front-End", category:"09-Stimulus-JS", path: "/fullstack-challenges/commits?path=04-Front-End/09-Stimulus-JS/02-Copy-To-Clipboard&committer=", langage: "Javascript", Optional: "false", name: "Copy to Clipboard" },
  repo146: { block:"04-Front-End", category:"09-Stimulus-JS", path: "/fullstack-challenges/commits?path=04-Front-End/09-Stimulus-JS/03-Character-Count&committer=", langage: "Javascript", Optional: "false", name: "Character Count" },
  repo147: { block:"04-Front-End", category:"09-Stimulus-JS", path: "/fullstack-challenges/commits?path=04-Front-End/09-Stimulus-JS/04-Checkboxes&committer=", langage: "Javascript", Optional: "false", name: "Check all Checkboxes" },
  repo148: { block:"04-Front-End", category:"09-Stimulus-JS", path: "/fullstack-challenges/commits?path=04-Front-End/09-Stimulus-JS/05-Stimulus-With-Plugins&committer=", langage: "Javascript", Optional: "false", name: "Charts with Stimulus" },
  repo149: { path: "/fullstack-challenges/commits?path=04-Front-End/10-Product-Design-Sprint/01-Schedule&committer=", langage: "Product Design", Optional: "false" },
  repo150: { path: "/fullstack-challenges/commits?path=04-Front-End/10-Product-Design-Sprint/01-What-You-Will-Build&committer=", langage: "Product Design", Optional: "false" },
  repo151: { path: "/fullstack-challenges/commits?path=04-Front-End/10-Product-Design-Sprint/02-Product-Pitch&committer=", langage: "Product Design", Optional: "false" },
  repo152: { path: "/fullstack-challenges/commits?path=04-Front-End/10-Product-Design-Sprint/03-Core-User-Journey&committer=", langage: "Product Design", Optional: "false" },
  repo153: { path: "/fullstack-challenges/commits?path=04-Front-End/10-Product-Design-Sprint/04-User-Flow&committer=", langage: "Product Design", Optional: "false" },
  repo154: { path: "/fullstack-challenges/commits?path=04-Front-End/10-Product-Design-Sprint/05-Basic-UI-Kit&committer=", langage: "Product Design", Optional: "false" },
  repo155: { path: "/fullstack-challenges/commits?path=04-Front-End/10-Product-Design-Sprint/06-UI-Kit-Advanced&committer=", langage: "Product Design", Optional: "false" },
  repo156: { path: "/fullstack-challenges/commits?path=04-Front-End/10-Product-Design-Sprint/07-Wireframe&committer=", langage: "Product Design", Optional: "false" },
  repo157: { path: "/fullstack-challenges/commits?path=04-Front-End/10-Product-Design-Sprint/08-Prototype&committer=", langage: "Product Design", Optional: "false" },
  repo158: { path: "/fullstack-challenges/commits?path=04-Front-End/10-Product-Design-Sprint/09-Pitch-Rehearsal&committer=", langage: "Product Design", Optional: "false" },
  repo159: { path: "/fullstack-challenges/commits?path=05-Rails/01-Rails-intro/01-HTTP-and-MVC-quiz&committer=", langage: "Rails", Optional: "false" },
  repo160: { path: "/commits?path=rails-stupid-coaching&committer=", langage: "Rails", Optional: "false" },
  repo161: { path: "/commits?path=rails-longest-word-game&committer=", langage: "Rails", Optional: "false" },
  repo162: { path: "/fullstack-challenges/commits?path=05-Rails/02-Rails-CRUD/01-Routing-quiz&committer=", langage: "Rails", Optional: "false" },
  repo163: { path: "/commits\?path\=rails-task-manager&committer=", langage: "Rails", Optional: "false" },
  repo164: { path: "/fullstack-challenges/commits?path=05-Rails/02-Rails-CRUD/03-Rails-Wikinimous&committer=", langage: "Rails", Optional: "false" },
  repo165: { path: "/fullstack-challenges/commits?path=05-Rails/03-Rails-restaurant-reviews/01-CRUD-quiz&committer=", langage: "Rails", Optional: "false" },
  repo166: { path: "/commits?path=rails-simple-airbnb&committer=", langage: "Rails", Optional: "false" },
  repo167: { path: "/commits?path=rails-simple-airbnb&committer=", langage: "Rails", Optional: "false" },
  repo168: { path: "/fullstack-challenges/commits?path=05-Rails/04-Rails-mister-cocktail/01-Advanced-routing-quiz&committer=", langage: "Rails", Optional: "false" },
  repo169: { path: "/fullstack-challenges/commits?path=05-Rails/04-Rails-mister-cocktail/02-Vue-Watch-List&committer=", langage: "Rails", Optional: "false" },
  repo170: { path: "/commits?path=rails-watch-list&committer=", langage: "Rails", Optional: "false" },
  repo171: { path: "/fullstack-challenges/commits?path=05-Rails/05-Rails/01-Rails-frontend-quiz&committer=", langage: "Rails", Optional: "false" },
  repo172: { path: "/fullstack-challenges/commits?path=05-Rails/05-Rails/01-Vue-Rails-frontend-quiz&committer=", langage: "Rails", Optional: "false" },
  repo173: { path: "/fullstack-challenges/commits?path=05-Rails/05-Rails/02-Watch-List-Images&committer=", langage: "Rails", Optional: "false" },
}


FRAME_LEVEL = {
  level1: { difficulty: "Débutant", min: 0, max: 25 },
  level2: { difficulty: "Intermédiaire", min: 25, max: 50 },
  level4: { difficulty: "Professionnel", min: 50, max: 300 }
}

  SKILL_LIST = {
    skill1: { name: "Ruby", wagon_level: 50, image_url: "Ruby.png" },
    skill2: { name: "JavaScript", wagon_level: 50, image_url: "JavaScript.png" },
    skill3: { name: "Python", wagon_level: 50, image_url: "Python.png" },
    skill4: { name: "Java", wagon_level: 50, image_url: "Java.png" },
    skill5: { name: "C++", wagon_level: 50, image_url: "C++.png" },
    skill6: { name: "TypeScript", wagon_level: 50, image_url: "TypeScript.png" },
    skill7: { name: "PHP", wagon_level: 50, image_url: "PHP.png" },
    skill8: { name: "React", wagon_level: 25, image_url: "React.png" },
    skill9: { name: "Node", wagon_level: 50, image_url: "Node.png" },
    skill10: { name: "Vue", wagon_level: 50, image_url: "Vue.png" },
    skill11: { name: "Database", wagon_level: 50, image_url: "Database.png" },
    skill12: { name: "Interview Preparation", wagon_level: 50, image_url: "Interview Preparation.png" },
    skill13: { name: "Product Design", wagon_level: 50, image_url: "Product Design.png" },
    skill14: { name: "Soft Skills", wagon_level: 50, image_url: "Soft Skills.png" },
  }
